### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by nrg51098** [nrg51098/tennis-partner-finder#11]
# User Stories
- [ ] As a user, when I am unauthenticated I should be able to see the Landing Page.
- [ ] As a user, when I am authenticated I should be able to perform all actions on the dashboard (full CRUD).
- [ ] As a user, I should be able to login via google.
- [ ] As a user, I should be able to logout.

# AC
**WHEN** a user is unauthenticated
**THEN** they can see the dashboard, but not edit it
**AND** when the user is authenticated
**THEN** they can sign in via google
**AND** they can perform all actions on the dashboard
**AND** they can successfully logout

# Dev Notes
### TODO:

- Login/Logout buttons are within the same `div` but display and hide depending on the User's login status
- Create a `checkLoginStatus()` function that checks Firebase for their login
- When logged out, print the dashboard as read-only
